### ISSUE TITLE
[13] Create the frontend mealplan view (FE)

### ISSUE THREAD

**Issue by wejama** [CEN3031-Spring2023-ProjectGroup50/SWEProject#127]

**Comment by shanhix1-personal** [comment]
- [ ] Add meals from API call to calendar view
- [ ] Click a meal on calendar to view details, edit, or delete (same as recipe details popup in Recipes page, but also with edit & delete buttons)
- [ ] Ability to edit dates & meal type on a meal (similar framework as edit recipe, using same form as "Add to meal plan" form)
- [ ] Ability to delete a meal

**Comment by shanhix1-personal** [comment]
View meal plan:
https://github.com/CEN3031-Spring2023-ProjectGroup50/SWEProject/pull/146

Click to view details:
https://github.com/CEN3031-Spring2023-ProjectGroup50/SWEProject/pull/148

Edit/delete:
https://github.com/CEN3031-Spring2023-ProjectGroup50/SWEProject/pull/150
