### ISSUE TITLE
[3] Backend: write search functions to get a recipe from the database

### ISSUE THREAD

**Issue by sethyboy20** [CEN3031-Spring2023-ProjectGroup50/SWEProject#25]
Done by Seth:
-function to return a single recipe by ID
-function to return all recipes in a slice

**Comment by sethyboy20** [comment]
Need to write more functions to get by search parameters (keywords, ingredients, etc.)

**Comment by wejama** [comment]
Keyword search functions (searches title, ingredients, instructions)
Ingredients only search also works for a list of ingredients. 
Need to add tests for these units of code.

**Comment by wejama** [comment]
Done.

**Comment by wejama** [comment]
- [ ] testing
