### ISSUE TITLE
[3] Investigate BE & FE image strategy (stretch goal)

### ISSUE THREAD

**Issue by shanhix1-personal** [CEN3031-Spring2023-ProjectGroup50/SWEProject#62]

**Comment by wejama** [comment]
Need to determine storage location for images. Targeting Saturday for a prototype solution.

**Comment by wejama** [comment]
Initial problem solved. 

- [ ] testing complete

**Comment by shanhix1-personal** [comment]
Leaving this item in progress & continuing to sprint 4. Assuming scope includes image upload.

**Comment by wejama** [comment]
Image upload completed.
