### ISSUE TITLE
[4] FE view recipe details experience

### ISSUE THREAD

**Issue by wejama** [CEN3031-Spring2023-ProjectGroup50/SWEProject#68]

**Comment by shanhix1-personal** [comment]
Merged these items into this single issue for ease of management:

- [4] Create FE screen to surface detailed recipe info (https://github.com/CEN3031-Spring2023-ProjectGroup50/SWEProject/issues/68)
- [4] Populate detailed recipe info onto screen (https://github.com/CEN3031-Spring2023-ProjectGroup50/SWEProject/issues/69)
- [4] routing to click from recipe card (entry point) to details screen, and to exit detail screen (https://github.com/CEN3031-Spring2023-ProjectGroup50/SWEProject/issues/70)

**Comment by shanhix1-personal** [comment]
Tutorial for passing objects between components:
https://dev.to/this-is-angular/passing-a-custom-angular-property-to-child-components-2966#:~:text=Passing%20data%20from%20parent%20to%20child%20components%20in,%28Parent.ts%29%20...%203%203.%20Use%20Property%20in%20Child.html
