### ISSUE TITLE
Frontend create recipe experience

### ISSUE THREAD

**Issue by shanhix1-personal** [CEN3031-Spring2023-ProjectGroup50/SWEProject#82]

**Comment by Em-Anderson** [comment]
Working - Currently WITHOUT implementing correct user ID or image services. Relies on proper formatting of ingredients list (per Shannon's parsing methods for the View Details experience) and does not appear in "All Recipes" or "User Created" lists. Will appear when key words are searched.

**Comment by Em-Anderson** [comment]
Now uses correct User ID, which was the issue propagating the bug where the recipes were not showing up in the all recipes tab. Recipes now display in the "all" filter and "user created" filters with the proper email.

- Still relies on proper formatting of ingredients per Shannon's parsing methods
